# Generated by Django 5.2.1 on 2025-06-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_collector',
            field=models.BooleanField(default=False),
        ),
    ]
