services:
  - type: web
    name: swaccha
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Swaccha_project.wsgi:application
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        sync: false
    autoDeploy: true
    postDeployCommand: |
      python manage.py migrate
