# Generated by Django 5.2.1 on 2025-06-10 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='dry_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='location',
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='booking',
            name='dry_types',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(choices=[('5:00 - 6:00', '5:00 - 6:00'), ('6:00 - 7:00', '6:00 - 7:00'), ('7:00 - 8:00', '7:00 - 8:00'), ('8:00 - 9:00', '8:00 - 9:00'), ('9:00 - 10:00', '9:00 - 10:00'), ('10:00 - 11:00', '10:00 - 11:00'), ('11:00 - 12:00', '11:00 - 12:00'), ('12:00 - 13:00', '12:00 - 13:00'), ('13:00 - 14:00', '13:00 - 14:00'), ('14:00 - 15:00', '14:00 - 15:00'), ('15:00 - 16:00', '15:00 - 16:00'), ('16:00 - 17:00', '16:00 - 17:00'), ('17:00 - 18:00', '17:00 - 18:00')], default='09:00 - 10:00', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='garbage_type',
            field=models.CharField(choices=[('wet', 'Wet'), ('dry', 'Dry')], max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='quantity',
            field=models.CharField(choices=[('0-20kg', 'Small (0-20kg)'), ('20-40kg', 'Medium (20-40kg)'), ('40-100kg', 'Large (40-100kg)')], max_length=20),
        ),
    ]
